# config.yaml
mode: "l7"

backends:
  - address: "127.0.0.1"
    port: 9001
    weight: 1
    path: "/api"
  - address: "127.0.0.1"
    port: 9002
    weight: 1
    path: "/static"
  - address: "127.0.0.1"
    port: 9003
    weight: 2
    path: "/api"

listen:
  address: "127.0.0.1"
  port: 8080

buffer_pool_size: 20
buffer_size: 8192