# config.yaml
backends:
  - address: "127.0.0.1"
    port: 9001
  - address: "127.0.0.1"
    port: 9002
  - address: "127.0.0.1"
    port: 9003

listen:
  address: "127.0.0.1"
  port: 8080

buffer_pool_size: 20
buffer_size: 8192